main: com.shanebeestudios.vf.VirtualFurnace
name: VirtualFurnace
version: '$version'
api-version: '$apiversion'
author: ShaneBee

commands:
  furnace:
    description: create a new furnace
    permission: virtualfurnace.command.furnace
